import type { ComponentsMessages } from '../zh-CN/components'

export const components: ComponentsMessages = {
  fileTree: {
    title: 'Project Files',
    refresh: 'Refresh file tree',
    empty: 'No files in the working directory yet',
    emptyHint: '(Code generated by the Agent will appear here)',
    openHint: '{path} (double-click to open)',
    openWave: 'Open waveform in GTKWave'
  },
  codeViewer: {
    findPlaceholder: 'Find in file',
    findAriaLabel: 'Find',
    noResults: 'No results',
    previous: 'Previous',
    next: 'Next',
    loading: 'Loading code viewer...'
  },
  errorBoundary: {
    title: 'A UI component crashed',
    description: 'MoonGlass has isolated this UI error; your project files and Agent sessions are intact. Reload the UI; if the problem recurs, use the details below to locate it.',
    reload: 'Reload UI'
  }
}
